### ISSUE TITLE
大佬是否考虑工作呢？字节跳动我们团队也有做技术架构的

### ISSUE THREAD

**Issue by huruji** [egoist/egoist.github.io#3]

**Comment by egoist** [comment]
不还意思有个字节跳动的女的天天骚扰我 https://twitter.com/siantgirl/status/1310373991572336640

**Comment by huruji** [comment]
哦哦，我不了解具体的缘由，就不做评价了，看样子好像是没机会合作了😭，如果你想要找工作的时候可以随时联系我，我下午也加了你的wx

**Comment by egoist** [comment]
给你分享下:

<img alt="bitch spam" src="https://user-images.githubusercontent.com/8784712/94995473-16937b80-05d1-11eb-8e05-edc48e1c67c4.png" width="400">

不过我不去字节是其它原因，毕竟一个人不能代表一个公司 😁

**Comment by huruji** [comment]
哦哦，sad，看到这个不知道该说啥😂，工作生活还是要分开的，总之还是那句话想要工作的时候可以联系我
